start_year: 1876  # First year to use
last_year: 2076   # Last year to use
run_forever: true # if true, ghcn_update will sleep polling_interval minutes, then check for new data
ghcn_bucket: noaa-ghcn-pds # bucket where GHCN CSV files are stored
ghcn_path: csv/  # folder path the GHCN CSV files
polling_interval: 1440  # 24 hours
hsds_endpoint: null  # HSDS endpoint - if HSDS is used
hsds_username: null  # HSDS username - if HSDS is used
hsds_password: null  # HSDS password - if HSDS is used
filename: null  # change to filepath to be used.  Use hdf5:// prefix for HSDS
log_level: INFO # DEBUG, INFO, WARNING, or ERROR
block_size: 1048576  # number of bytes to read from S3 per request
